name: face_recog
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - face-recognition
  - dlib
  - opencv
  - scikit-learn
  - numpy
  - scipy
  - imutils
  - python-dotenv
  - pyyaml
  - pip
  - pip:
      - face-recognition-models
